#!/bin/bash
set -e

REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}

mkdir -p "$GITHUB_WORKSPACE/$INPUT_LOCATION"
zip -rq  "$GITHUB_WORKSPACE/$INPUT_LOCATION/$REPO_NAME.zip" . -x "*.git*" -x "*${INPUT_LOCATION}*"

echo "path=$INPUT_LOCATION/$REPO_NAME.zip" >> "$GITHUB_OUTPUT"
echo "full_path=$GITHUB_WORKSPACE/$INPUT_LOCATION/$REPO_NAME.zip" >> "$GITHUB_OUTPUT"
